### PR TITLE
add 'http' to external links

### PR DESCRIPTION
**Pull request by radomishel**

### CODE REVIEW

**Comment by lukecampbell** [comment]
oh, they don't support https?

**Comment by lukecampbell** [comment]
Hey Ben in the future could you push to the [ioos/hfradar-dac-landing](https://github.com/ioos/hfradar-dac-landing/) ?

**Comment by radomishel** [comment]
@lukecampbell yes! hadn't realized there was a repo there

**Comment by lukecampbell** [comment]
Yeah sorry I created it this morning, I had to check in with IOOS that it was ok to move it there.

**Comment by lukecampbell** [comment]
If you could make a PR now, that would be tremendously helpful

**Pull request merged**
